import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const direction = readFileSync(join(import.meta.dirname, '../docs/DIRECTION.md'), 'utf8')

describe('radar §9 closed (ZEE-13)', () => {
  it('records stand-in construction and hand-wired main as the language', () => {
    expect(direction).toMatch(/33\.\s+\*\*Construction\*\*/)
    expect(direction).toMatch(/34\.\s+\*\*Composition\*\*/)
    expect(direction).toContain('## 9. Radar (closed)')
    expect(direction).not.toContain('## 9. Radar (not closed)')
    expect(direction).toContain('No `new`')
    expect(direction).toContain('No `@Inject`')
    expect(direction).toContain('`http.app()`')
    expect(direction).toContain('indexes `@Controller`')
  })

  it('defines the collection and emptiness catalogs without a second grammar', () => {
    expect(direction).toMatch(/35\.\s+\*\*Collection methods\*\*/)
    expect(direction).toMatch(/36\.\s+\*\*Emptiness\*\*/)
    expect(direction).toContain('### 8f. Collection methods')
    expect(direction).toContain('### 8g. Emptiness, blank, none')
    expect(direction).toContain('`forEach`')
    expect(direction).toContain('`any`')
    expect(direction).toContain('`isEmpty`')
    expect(direction).toMatch(/37\.\s+\*\*Project kinds\*\*/)
    expect(direction).toContain('--kind bin|api|web|monolith|service')
    expect(direction).toMatch(/38\.\s+\*\*JSON\*\*/)
    expect(direction).toContain('json.encode')
    expect(direction).toContain('json.decode')
    expect(direction).toMatch(/39\.\s+\*\*HTTP\*\*/)
    expect(direction).toContain('http.listen')
    expect(direction).toContain('http.router()')
    expect(direction).toContain('The compiler does not know Get/Post')
    expect(direction).toContain('@Param("id")')
    expect(direction).toContain('@PathPrefix("/api")')
    expect(direction).toContain('@Cors')
    expect(direction).toContain('HttpCode')
    expect(direction).toContain('http.response')
    expect(direction).toContain('http.abort')
    expect(direction).toContain('@ErrorHandler')
    expect(direction).toContain('`index` / `create` / `store` / `show` / `edit` / `update` / `destroy`')
    expect(direction).toContain('apiResource()')
    expect(direction).toContain('ApiResource')
    expect(direction).toContain('Not a `src/` walk')
    expect(direction).toMatch(/40\.\s+\*\*Attributes\*\*/)
    expect(direction).toContain('The package that implements the name')
    expect(direction).toContain('src/bootstrap/')
    expect(direction).toContain('src/shared/')
    expect(direction).toContain('`test/`')
  })
})
